//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.6.3
//     from Assets/InputActions.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @InputActions: IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @InputActions()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""InputActions"",
    ""maps"": [
        {
            ""name"": ""PlayerDefault"",
            ""id"": ""1cb6dbfc-564f-4da3-aec2-45ed3d14b09f"",
            ""actions"": [
                {
                    ""name"": ""Movement"",
                    ""type"": ""Value"",
                    ""id"": ""1a4dda47-2ffe-4761-b856-841926bf8448"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""CastSpell"",
                    ""type"": ""Button"",
                    ""id"": ""0ea5847e-7631-41a2-ab19-9566c36ab4af"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""AddOrb1"",
                    ""type"": ""Button"",
                    ""id"": ""debccc8d-82c1-473c-a063-9e871afa4404"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""AddOrb2"",
                    ""type"": ""Button"",
                    ""id"": ""5699c79b-00ff-4fbd-bf5b-f2dfa79abd02"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""AddOrb3"",
                    ""type"": ""Button"",
                    ""id"": ""4509d393-0c2d-48b3-beee-74525d972994"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""AddOrb4"",
                    ""type"": ""Button"",
                    ""id"": ""3f1587dc-e80d-4b09-94c3-23078b32ada4"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""AddOrb5"",
                    ""type"": ""Button"",
                    ""id"": ""f6a0f3f4-9357-4692-9261-ef84550122b5"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""AddOrb6"",
                    ""type"": ""Button"",
                    ""id"": ""ead116a1-348f-4b9e-a2bc-103df47a39a4"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": ""2D Vector WASD"",
                    ""id"": ""95b522b3-dbbd-488b-aabc-36e0f066c130"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movement"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""8442b1e9-262b-421f-9ae0-bcd981fa0095"",
                    ""path"": ""<Keyboard>/w"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""d00fb70f-cad7-4fc8-8087-1c23bc695c8c"",
                    ""path"": ""<Keyboard>/s"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""f862473a-c5b3-4aab-ae21-902c50d297ac"",
                    ""path"": ""<Keyboard>/a"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""9f9d0ebd-b51a-4f2f-9e47-053c6b54b2dd"",
                    ""path"": ""<Keyboard>/d"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""642dbb8b-e585-4c1e-a3b6-25779f4be88f"",
                    ""path"": ""<Mouse>/leftButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""CastSpell"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""a83f63c9-9125-4b64-8302-adb65535deb5"",
                    ""path"": ""<Keyboard>/numpad1"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""AddOrb1"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""228eace9-3cca-453e-9273-17ce523db795"",
                    ""path"": ""<Keyboard>/numpad2"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""AddOrb2"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""3f71478a-f884-44bd-8361-ce4683439c7b"",
                    ""path"": ""<Keyboard>/numpad3"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""AddOrb3"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""266b5732-4801-4062-a0d9-8dceb9aef1d2"",
                    ""path"": ""<Keyboard>/numpad4"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""AddOrb4"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""e6ef41df-5fbf-4522-b2d8-64b7684d6a4f"",
                    ""path"": ""<Keyboard>/numpad5"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""AddOrb5"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""0f67ddd1-385e-40a6-ba19-412bcc79448e"",
                    ""path"": ""<Keyboard>/numpad6"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""AddOrb6"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // PlayerDefault
        m_PlayerDefault = asset.FindActionMap("PlayerDefault", throwIfNotFound: true);
        m_PlayerDefault_Movement = m_PlayerDefault.FindAction("Movement", throwIfNotFound: true);
        m_PlayerDefault_CastSpell = m_PlayerDefault.FindAction("CastSpell", throwIfNotFound: true);
        m_PlayerDefault_AddOrb1 = m_PlayerDefault.FindAction("AddOrb1", throwIfNotFound: true);
        m_PlayerDefault_AddOrb2 = m_PlayerDefault.FindAction("AddOrb2", throwIfNotFound: true);
        m_PlayerDefault_AddOrb3 = m_PlayerDefault.FindAction("AddOrb3", throwIfNotFound: true);
        m_PlayerDefault_AddOrb4 = m_PlayerDefault.FindAction("AddOrb4", throwIfNotFound: true);
        m_PlayerDefault_AddOrb5 = m_PlayerDefault.FindAction("AddOrb5", throwIfNotFound: true);
        m_PlayerDefault_AddOrb6 = m_PlayerDefault.FindAction("AddOrb6", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }

    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }

    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // PlayerDefault
    private readonly InputActionMap m_PlayerDefault;
    private List<IPlayerDefaultActions> m_PlayerDefaultActionsCallbackInterfaces = new List<IPlayerDefaultActions>();
    private readonly InputAction m_PlayerDefault_Movement;
    private readonly InputAction m_PlayerDefault_CastSpell;
    private readonly InputAction m_PlayerDefault_AddOrb1;
    private readonly InputAction m_PlayerDefault_AddOrb2;
    private readonly InputAction m_PlayerDefault_AddOrb3;
    private readonly InputAction m_PlayerDefault_AddOrb4;
    private readonly InputAction m_PlayerDefault_AddOrb5;
    private readonly InputAction m_PlayerDefault_AddOrb6;
    public struct PlayerDefaultActions
    {
        private @InputActions m_Wrapper;
        public PlayerDefaultActions(@InputActions wrapper) { m_Wrapper = wrapper; }
        public InputAction @Movement => m_Wrapper.m_PlayerDefault_Movement;
        public InputAction @CastSpell => m_Wrapper.m_PlayerDefault_CastSpell;
        public InputAction @AddOrb1 => m_Wrapper.m_PlayerDefault_AddOrb1;
        public InputAction @AddOrb2 => m_Wrapper.m_PlayerDefault_AddOrb2;
        public InputAction @AddOrb3 => m_Wrapper.m_PlayerDefault_AddOrb3;
        public InputAction @AddOrb4 => m_Wrapper.m_PlayerDefault_AddOrb4;
        public InputAction @AddOrb5 => m_Wrapper.m_PlayerDefault_AddOrb5;
        public InputAction @AddOrb6 => m_Wrapper.m_PlayerDefault_AddOrb6;
        public InputActionMap Get() { return m_Wrapper.m_PlayerDefault; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(PlayerDefaultActions set) { return set.Get(); }
        public void AddCallbacks(IPlayerDefaultActions instance)
        {
            if (instance == null || m_Wrapper.m_PlayerDefaultActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_PlayerDefaultActionsCallbackInterfaces.Add(instance);
            @Movement.started += instance.OnMovement;
            @Movement.performed += instance.OnMovement;
            @Movement.canceled += instance.OnMovement;
            @CastSpell.started += instance.OnCastSpell;
            @CastSpell.performed += instance.OnCastSpell;
            @CastSpell.canceled += instance.OnCastSpell;
            @AddOrb1.started += instance.OnAddOrb1;
            @AddOrb1.performed += instance.OnAddOrb1;
            @AddOrb1.canceled += instance.OnAddOrb1;
            @AddOrb2.started += instance.OnAddOrb2;
            @AddOrb2.performed += instance.OnAddOrb2;
            @AddOrb2.canceled += instance.OnAddOrb2;
            @AddOrb3.started += instance.OnAddOrb3;
            @AddOrb3.performed += instance.OnAddOrb3;
            @AddOrb3.canceled += instance.OnAddOrb3;
            @AddOrb4.started += instance.OnAddOrb4;
            @AddOrb4.performed += instance.OnAddOrb4;
            @AddOrb4.canceled += instance.OnAddOrb4;
            @AddOrb5.started += instance.OnAddOrb5;
            @AddOrb5.performed += instance.OnAddOrb5;
            @AddOrb5.canceled += instance.OnAddOrb5;
            @AddOrb6.started += instance.OnAddOrb6;
            @AddOrb6.performed += instance.OnAddOrb6;
            @AddOrb6.canceled += instance.OnAddOrb6;
        }

        private void UnregisterCallbacks(IPlayerDefaultActions instance)
        {
            @Movement.started -= instance.OnMovement;
            @Movement.performed -= instance.OnMovement;
            @Movement.canceled -= instance.OnMovement;
            @CastSpell.started -= instance.OnCastSpell;
            @CastSpell.performed -= instance.OnCastSpell;
            @CastSpell.canceled -= instance.OnCastSpell;
            @AddOrb1.started -= instance.OnAddOrb1;
            @AddOrb1.performed -= instance.OnAddOrb1;
            @AddOrb1.canceled -= instance.OnAddOrb1;
            @AddOrb2.started -= instance.OnAddOrb2;
            @AddOrb2.performed -= instance.OnAddOrb2;
            @AddOrb2.canceled -= instance.OnAddOrb2;
            @AddOrb3.started -= instance.OnAddOrb3;
            @AddOrb3.performed -= instance.OnAddOrb3;
            @AddOrb3.canceled -= instance.OnAddOrb3;
            @AddOrb4.started -= instance.OnAddOrb4;
            @AddOrb4.performed -= instance.OnAddOrb4;
            @AddOrb4.canceled -= instance.OnAddOrb4;
            @AddOrb5.started -= instance.OnAddOrb5;
            @AddOrb5.performed -= instance.OnAddOrb5;
            @AddOrb5.canceled -= instance.OnAddOrb5;
            @AddOrb6.started -= instance.OnAddOrb6;
            @AddOrb6.performed -= instance.OnAddOrb6;
            @AddOrb6.canceled -= instance.OnAddOrb6;
        }

        public void RemoveCallbacks(IPlayerDefaultActions instance)
        {
            if (m_Wrapper.m_PlayerDefaultActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(IPlayerDefaultActions instance)
        {
            foreach (var item in m_Wrapper.m_PlayerDefaultActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_PlayerDefaultActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public PlayerDefaultActions @PlayerDefault => new PlayerDefaultActions(this);
    public interface IPlayerDefaultActions
    {
        void OnMovement(InputAction.CallbackContext context);
        void OnCastSpell(InputAction.CallbackContext context);
        void OnAddOrb1(InputAction.CallbackContext context);
        void OnAddOrb2(InputAction.CallbackContext context);
        void OnAddOrb3(InputAction.CallbackContext context);
        void OnAddOrb4(InputAction.CallbackContext context);
        void OnAddOrb5(InputAction.CallbackContext context);
        void OnAddOrb6(InputAction.CallbackContext context);
    }
}
